name: Next.js CI/CD

on:
  push:
    branches:
      - mukti
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      # ---------- QA ----------
      - name: Deploy QA
        if: github.ref == 'refs/heads/mukti'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: ".next,public,package.json,package-lock.json"
          target: ${{ secrets.QA_PATH }}
          rm: true

      - name: Start / Restart QA
        if: github.ref == 'refs/heads/mukti'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/qa/RozgarUserJobList
            npm install --omit=dev
            pm2 delete rozgar-qa || true
            PORT=9999 pm2 start npm --name "rozgar-qa" -- start 
            pm2 save

      # ---------- PROD ----------
      - name: Deploy PROD
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: ".next,public,package.json,package-lock.json"
          target: ${{ secrets.PROD_PATH }}
          rm: true

      - name: Start / Restart PROD
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/prod/RozgarUserJobList
            npm install --omit=dev
            pm2 delete rozgar-prod || true
            PORT=8888 pm2 start npm --name "rozgar-prod" -- start 
            pm2 save